### ISSUE TITLE
Print whom to can ping for an approval

### ISSUE THREAD

**Issue by ggwpez** [paritytech/review-bot#109]
Eg the output here tells me that it counted Basti and needs more rank 3 approvals: https://github.com/polkadot-fellows/runtimes/pull/133/checks?check_run_id=20196675519

Maybe it can also list all people that i can ping? I think the info should be available, or?

**Comment by Bullrich** [comment]
Hi @ggwpez!

This has been done in #112

Version `2.4.0` prints two lists:
- One which shows whose review counts towards an unfulfilled rule.
- One which shows which users' approval _would_ count towards this rule, so with this you can request their reviews

The PR to update Review-bot to `2.4.0` are the following:
- paritytech/polkadot-sdk#3119
- polkadot-fellows/runtimes#168

You can find a working example [here 📗](https://github.com/paritytech/polkadot-sdk/actions/runs/7784001486)

I hope this fulfills your request 😃
