### ISSUE TITLE
Make Review-Bot fetch the latest information of a PR instead of using the action payload

### ISSUE THREAD

**Issue by rzadp** [paritytech/review-bot#122]
Here: https://github.com/polkadot-fellows/runtimes/pull/314

The last commit and the approval came within 1 minute of each other.
Possibly it created a race condition, resulting in a bug - re-requesting an approval, which was unexpected.

**Comment by Bullrich** [comment]
Solution

Make review-bot fetch the latest information of the PR and not use the event.

**Comment by Bullrich** [comment]
This was already solved in #94
